### ISSUE TITLE
Test descriptions

### ISSUE THREAD

**Issue by micahshute** [learn-co-curriculum/building-forms-lab#16]
The second test displays the following upon failure: `BandInput has an initial state with text key set to empty string`, but the tests are looking for a `name` key, not a `text` key.

**Comment by maxwellbenton** [comment]
Hi @micahshute,

Thank you for spotting this and providing feedback. We've merged in a fix that updates this test and its instructions so that they specify `name`.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
